# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocol_pb2 as protocol__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistributedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeMethod = channel.unary_unary(
                '/enhanced_mcp.DistributedService/InvokeMethod',
                request_serializer=protocol__pb2.MethodRequest.SerializeToString,
                response_deserializer=protocol__pb2.MethodResponse.FromString,
                _registered_method=True)
        self.SubscribeToEvents = channel.unary_stream(
                '/enhanced_mcp.DistributedService/SubscribeToEvents',
                request_serializer=protocol__pb2.EventSubscription.SerializeToString,
                response_deserializer=protocol__pb2.EventNotification.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/enhanced_mcp.DistributedService/HealthCheck',
                request_serializer=protocol__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=protocol__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.DiscoverCapabilities = channel.unary_unary(
                '/enhanced_mcp.DistributedService/DiscoverCapabilities',
                request_serializer=protocol__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=protocol__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)


class DistributedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InvokeMethod(self, request, context):
        """Basic request-response for method invocation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToEvents(self, request, context):
        """Streaming API for events/notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for fault tolerance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverCapabilities(self, request, context):
        """Capability discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMethod,
                    request_deserializer=protocol__pb2.MethodRequest.FromString,
                    response_serializer=protocol__pb2.MethodResponse.SerializeToString,
            ),
            'SubscribeToEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToEvents,
                    request_deserializer=protocol__pb2.EventSubscription.FromString,
                    response_serializer=protocol__pb2.EventNotification.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=protocol__pb2.HealthCheckRequest.FromString,
                    response_serializer=protocol__pb2.HealthCheckResponse.SerializeToString,
            ),
            'DiscoverCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverCapabilities,
                    request_deserializer=protocol__pb2.DiscoveryRequest.FromString,
                    response_serializer=protocol__pb2.CapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enhanced_mcp.DistributedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enhanced_mcp.DistributedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DistributedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InvokeMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enhanced_mcp.DistributedService/InvokeMethod',
            protocol__pb2.MethodRequest.SerializeToString,
            protocol__pb2.MethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/enhanced_mcp.DistributedService/SubscribeToEvents',
            protocol__pb2.EventSubscription.SerializeToString,
            protocol__pb2.EventNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enhanced_mcp.DistributedService/HealthCheck',
            protocol__pb2.HealthCheckRequest.SerializeToString,
            protocol__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enhanced_mcp.DistributedService/DiscoverCapabilities',
            protocol__pb2.DiscoveryRequest.SerializeToString,
            protocol__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
